export const CHANGE_TOPBANNERS = 'CHANGE_TOPBANNERS';
export const CHANGE_HOTRECOMMENDS = 'CHANGE_HOTRECOMMENDS';
export const CHANGE_NEWALBUMS = 'CHANGE_NEWALBUMS';
export const CHANGE_TOPLIST = 'CHANGE_TOPLIST';
export const CHANGE_UP_RANKING = 'CHANGE_UP_RANKING';
export const CHANGE_NEW_RANKING = 'CHANGE_NEW_RANKING';
export const CHANGE_ORIGIN_RANKING = 'CHANGE_ORIGIN_RANKING';
