export const CHANGE_ALL_TOPLIST = 'CHANGE_ALL_TOPLIST';
export const CHANGE_CURRENT_TOPLIST_INFO = 'CHANGE_CURRENT_TOPLIST_INFO';
export const CHANGE_CURRENT_TOPLIST_SONGS = 'CHANGE_CURRENT_TOPLIST_SONGS';
export const CHANGE_CURRENT_ID = 'CHANGE_CURRENT_ID';
